[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

eth_rpc_url = 'https://eth-sepolia.g.alchemy.com/v2/vKiwVouOiUHZFlx9l7uGdRmpab9d88Ee'
etherscan_api_key = 'QW26GSPII3IRNKQKA3ET3M1XWQ5N3HVEWZ'